<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWywJ7cd\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWywJ7cd/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWywJ7cd.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWywJ7cd\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWywJ7cd\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'WywJ7cd',
    'container.build_id' => '34630ab6',
    'container.build_time' => 1542110625,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWywJ7cd');
